In [1]:
import pandas as pd
from utils import *
from constant import *

In [2]:
len(data_df)

450

In [8]:
df = pd.read_csv("output6.csv",index_col=0)
df = df[~df["mean"].duplicated()]
df = df[df["count"] > 30]
filterss = [list(df.index)]

In [9]:
dfs = []
for filters in filterss:
    for filter_key in filters:
        to_filter = getFilter(filter_key) & ~yz2
        sub_df = data_df[to_filter]
        if len(sub_df) > 0:
            mean = sub_df.change.mean()
            win_df = sub_df[sub_df["change"] > 1.0]
            win_ratio = float(len(win_df))/len(sub_df)
            print filter_key,mean,win_ratio,
            print list(sub_df.index)
            print "----"
            dfs.append(sub_df)
df = pd.concat(dfs)

 small_volume-yz0-~yz1-top1-opentop1 0.918145750679 0.0 ['002875.XSHE_2017-06-12']
----
jump2-~foot1-small_volume-yz0-~opentop1-top1 0.886073796973 0.0 ['603383.XSHG_2017-06-05']
----
~speedup1-jump1-speedup2-small_volume-top1-opentop1 1.02444703143 1.0 ['002047.XSHE_2017-06-08']
----
~opentop2-~speedup1-small_volume-top1-opentop1 0.971296391054 0.5 ['002047.XSHE_2017-06-08', '002875.XSHE_2017-06-12']
----
~opentop2-jump1-~speedup2-foot0-foot2-small_volume 0.843960990248 0.0 ['300526.XSHE_2017-06-09']
----
~speedup1-~jump2-foot0-foot2-small_volume 0.918913923196 0.0 ['000726.XSHE_2017-06-01', '002842.XSHE_2017-06-08', '300465.XSHE_2017-06-15', '300526.XSHE_2017-06-09']
----
~speedup1-~jump1-speedup2-~jump2-foot2-small_volume-top0 1.03815208928 1.0 ['300657.XSHE_2017-06-15']
----
~speedup1-~jump1-jump2-~foot2-small_volume-top0 0.886073796973 0.0 ['603383.XSHG_2017-06-05']
----

/Users/sgcy/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [4]:
df

,change,close0,close1,close2,close3,date,day0,day1,day2,day3,...,vol60,volume0,volume1,volume2,volume3,volume_high,volume_mean,wave,st,isnew
002875.XSHE_2017-06-12,0.918146,39.58,43.54,47.74,44.90,2017-06-12 00:00:00,5.0,6.0,7.0,8.0,...,NaN,87406.0,12749386.0,17804780.0,13346763.0,41706.0,NaN,0,False,1.0
603383.XSHG_2017-06-05,0.886074,48.60,53.46,54.22,53.01,2017-06-05 00:00:00,6.0,7.0,8.0,9.0,...,NaN,300419.0,13615568.0,9855938.0,11410669.0,57624.0,NaN,0,False,1.0
002047.XSHE_2017-06-08,1.024447,7.10,7.81,8.59,8.97,2017-06-08 00:00:00,100.0,101.0,102.0,103.0,...,NaN,9645055.0,60579854.0,44146172.0,115661258.0,32073552.0,7.605966e+06,0,False,0.0
002047.XSHE_2017-06-08,1.024447,7.10,7.81,8.59,8.97,2017-06-08 00:00:00,100.0,101.0,102.0,103.0,...,NaN,9645055.0,60579854.0,44146172.0,115661258.0,32073552.0,7.605966e+06,0,False,0.0
002875.XSHE_2017-06-12,0.918146,39.58,43.54,47.74,44.90,2017-06-12 00:00:00,5.0,6.0,7.0,8.0,...,NaN,87406.0,12749386.0,17804780.0,13346763.0,41706.0,NaN,0,False,1.0
300526.XSHE_2017-06-09,0.843961,34.65,36.35,37.50,33.75,2017-06-09 00:00:00,7.0,8.0,9.0,10.0,...,NaN,4843777.0,18911560.0,20593569.0,14878970.0,24319756.0,8.004371e+06,0,False,1.0
000726.XSHE_2017-06-01,0.908517,11.34,11.53,11.60,11.60,2017-06-01 00:00:00,95.0,96.0,97.0,98.0,...,NaN,2289397.0,6472793.0,9887266.0,8195881.0,19433291.0,5.795986e+06,0,False,0.0
002842.XSHE_2017-06-08,0.930086,34.64,36.02,36.95,38.35,2017-06-08 00:00:00,88.0,89.0,90.0,91.0,...,NaN,597910.0,1517867.0,2697790.0,2920557.0,15786170.0,4.416550e+06,0,False,1.0
300465.XSHE_2017-06-15,0.993092,10.00,10.53,11.58,11.04,2017-06-15 00:00:00,79.0,80.0,81.0,82.0,...,NaN,14016167.0,18533442.0,31156506.0,22971868.0,19166495.0,8.382748e+06,0,False,0.0
300526.XSHE_2017-06-09,0.843961,34.65,36.35,37.50,33.75,2017-06-09 00:00:00,7.0,8.0,9.0,10.0,...,NaN,4843777.0,18911560.0,20593569.0,14878970.0,24319756.0,8.004371e+06,0,False,1.0
300657.XSHE_2017-06-15,1.038152,38.62,35.03,38.53,39.39,2017-06-15 00:00:00,13.0,14.0,15.0,16.0,...,NaN,7732663.0,16620433.0,6986592.0,16395786.0,1486309.0,NaN,0,False,1.0
603383.XSHG_2017-06-05,0.886074,48.60,53.46,54.22,53.01,2017-06-05 00:00:00,6.0,7.0,8.0,9.0,...,NaN,300419.0,13615568.0,9855938.0,11410669.0,57624.0,NaN,0,False,1.0

In [5]:
df = data_df

In [10]:
df = df[~df.index.duplicated()] 
df = df.sort_values("minute")
df = df.groupby("date").first()
win_df = df[df["change"] > 1.0]
win_ratio = float(len(win_df))/len(df)
print df.change.mean(),win_ratio

0.936549501461 0.333333333333

In [11]:
len(df)

6

In [18]:
len(df),len(data_df)

(1050, 10246)

In [12]:
df

,change,close0,close1,close2,close3,day0,day1,day2,day3,gap_low,...,vol60,volume0,volume1,volume2,volume3,volume_high,volume_mean,wave,st,isnew
date,,,,,,,,,,,,,,,,,,,,,
2017-06-01 00:00:00,0.908517,11.34,11.53,11.60,11.60,95.0,96.0,97.0,98.0,NaN,...,NaN,2289397.0,6472793.0,9887266.0,8195881.0,19433291.0,5.795986e+06,0,False,0.0
2017-06-05 00:00:00,0.886074,48.60,53.46,54.22,53.01,6.0,7.0,8.0,9.0,NaN,...,NaN,300419.0,13615568.0,9855938.0,11410669.0,57624.0,NaN,0,False,1.0
2017-06-08 00:00:00,1.024447,7.10,7.81,8.59,8.97,100.0,101.0,102.0,103.0,NaN,...,NaN,9645055.0,60579854.0,44146172.0,115661258.0,32073552.0,7.605966e+06,0,False,0.0
2017-06-09 00:00:00,0.843961,34.65,36.35,37.50,33.75,7.0,8.0,9.0,10.0,NaN,...,NaN,4843777.0,18911560.0,20593569.0,14878970.0,24319756.0,8.004371e+06,0,False,1.0
2017-06-12 00:00:00,0.918146,39.58,43.54,47.74,44.90,5.0,6.0,7.0,8.0,NaN,...,NaN,87406.0,12749386.0,17804780.0,13346763.0,41706.0,NaN,0,False,1.0
2017-06-15 00:00:00,1.038152,38.62,35.03,38.53,39.39,13.0,14.0,15.0,16.0,NaN,...,NaN,7732663.0,16620433.0,6986592.0,16395786.0,1486309.0,8.382748e+06,0,False,1.0

In [20]:
print df.ix[-1]

change                      0.934415
date             2017-04-17 00:00:00
stock                    603616.XSHG
close0                         23.44
high0                          23.44
high_limit0                    23.44
low0                           23.44
open0                          23.44
volume0                  1.39253e+06
day0                             436
close1                         25.78
high1                          25.78
high_limit1                    25.78
low1                           25.78
open1                          25.78
volume1                  1.63859e+06
day1                             437
close2                         27.94
high2                          28.36
high_limit2                    28.36
low2                           26.39
open2                          28.36
volume2                   7.4573e+07
day2                             438
close3                         28.65
high3                          29.94
high_limit3                    30.73
low3                           25.39
open3                           26.5
volume3                  5.68551e+07
day3                             439
minute_low                     27.69
minute_volume                      0
minute                      09:30:00
recent                             7
circap                          1143
isnew                              0
capq                        0.346574
st                             False
Name: 603616.XSHG_2017-04-17, dtype: object

In [21]:
data_df = data_df.sort_values("minute")
data_df = data_df.groupby("date").first()
win_df = data_df[data_df["change"] > 1.0]
win_ratio = float(len(win_df))/len(data_df)
print data_df.change.mean(),win_ratio

0.992634761652 0.436403508772

In [4]:
data_df

,change,stock,close0,high0,high_limit0,low0,open0,volume0,day0,close1,...,volume3,day3,recent,minute_low,minute_volume,minute,st,circap,isnew,capq
date,,,,,,,,,,,,,,,,,,,,,
2017-05-04 00:00:00,1.061268,603616.XSHG,27.80,27.80,27.80,24.41,25.37,34388364.0,0.0,29.97,...,81594848.0,3.0,1.0,32.20,0.0,09:30:00,False,1510.0,False,0.456331
2017-05-05 00:00:00,0.964533,600581.XSHG,9.55,9.55,9.55,8.88,8.93,66374422.0,0.0,10.51,...,142481708.0,3.0,3.0,11.00,13831100.0,09:31:00,False,2330.0,False,0.704140
2017-05-08 00:00:00,0.850437,300534.XSHE,72.88,75.45,83.45,72.32,74.93,3332581.0,2.0,80.17,...,7485700.0,5.0,2.0,24.69,1985366.0,09:31:00,False,388.5,False,0.117407
2017-05-09 00:00:00,1.210269,002350.XSHE,16.90,17.25,18.71,16.76,16.80,1600783.0,3.0,18.59,...,895214.0,6.0,2.0,19.39,4559200.0,09:31:00,False,1425.0,False,0.430644
2017-05-10 00:00:00,0.943703,300481.XSHE,25.40,26.94,27.10,24.61,24.64,5763205.0,4.0,27.94,...,20989832.0,7.0,2.0,29.18,2773786.0,09:32:00,False,539.0,False,0.162889
2017-05-11 00:00:00,1.047619,002865.XSHE,30.72,30.72,30.72,26.95,27.50,12791387.0,5.0,33.79,...,18733085.0,8.0,8.0,31.88,16809800.0,14:28:00,False,178.0,True,0.053793
2017-05-12 00:00:00,1.077338,002868.XSHE,35.26,35.26,35.26,35.26,35.26,40950.0,5.0,38.79,...,17519293.0,8.0,8.0,41.58,0.0,09:30:00,False,253.0,True,0.076458
2017-05-15 00:00:00,1.066886,002282.XSHE,20.14,20.14,20.14,17.90,18.32,40442093.0,7.0,22.15,...,75888049.0,10.0,3.0,23.97,0.0,09:30:00,False,1526.5,False,0.461318
2017-05-16 00:00:00,1.043904,603787.XSHG,22.77,22.77,22.77,22.77,22.77,295691.0,8.0,25.05,...,20812984.0,11.0,11.0,27.25,0.0,09:30:00,False,284.0,True,0.085827
2017-05-17 00:00:00,0.989011,300021.XSHE,20.31,20.85,22.42,20.00,20.10,8786160.0,9.0,22.34,...,47655589.0,12.0,2.0,9.72,0.0,09:30:00,False,1240.0,False,0.374736
2017-05-18 00:00:00,0.963527,603728.XSHG,26.05,26.05,26.05,26.05,26.05,284239.0,5.0,28.66,...,27056559.0,8.0,8.0,30.88,7381500.0,09:32:00,False,671.0,True,0.202780
2017-05-19 00:00:00,0.794036,603501.XSHG,23.84,23.84,23.84,23.84,23.84,164176.0,9.0,26.22,...,12357647.0,12.0,12.0,28.00,0.0,09:30:00,False,121.0,True,0.036567
2017-05-22 00:00:00,0.924207,002350.XSHE,24.75,24.75,24.75,24.75,24.75,1223379.0,7.0,27.23,...,52191586.0,10.0,6.0,28.20,9066600.0,09:32:00,False,1874.0,False,0.566334
2017-05-23 00:00:00,0.909832,300140.XSHE,19.24,19.24,19.24,18.17,18.37,24376114.0,13.0,18.95,...,59912983.0,16.0,1.0,18.15,36444400.0,13:36:00,False,1701.0,False,0.514053
2017-05-24 00:00:00,1.210140,300649.XSHE,37.16,37.16,37.16,37.16,37.16,124500.0,11.0,40.88,...,3961100.0,14.0,14.0,42.88,0.0,09:30:00,False,46.0,True,0.013901
2017-05-25 00:00:00,0.968523,603505.XSHG,20.48,20.48,20.48,20.11,20.48,25106749.0,14.0,22.53,...,42141600.0,17.0,17.0,24.20,0.0,09:30:00,False,326.0,True,0.098519
2017-05-26 00:00:00,NaN,002350.XSHE,27.30,27.45,30.35,24.83,24.83,44330778.0,11.0,30.03,...,NaN,NaN,2.0,32.50,0.0,09:30:00,False,2198.5,False,0.664400

In [7]:
data_df = pd.read_csv("top3.csv",index_col=0, parse_dates=True)
len(data_df)

144

In [8]:
data_df = data_df.sort(["change"])
data_df.tail(20)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,change,date,stock,close0,high0,high_limit0,low0,open0,volume0,day0,...,volume3,day3,recent,minute_low,minute_volume,minute,st,circap,isnew,capq
603603.XSHG_2017-05-12,1.056995,2017-05-12 00:00:00,603603.XSHG,38.28,38.93,39.72,37.10,38.00,14140203.0,6.0,...,25187437.0,9.0,2.0,45.33,2493900.0,09:31:00,False,439.0,False,0.132668
603098.XSHG_2017-05-25,1.061008,2017-05-25 00:00:00,603098.XSHG,21.81,23.68,26.65,21.81,23.18,10025643.0,15.0,...,34045394.0,18.0,2.0,25.22,6670400.0,09:39:00,False,414.0,False,0.125113
603616.XSHG_2017-05-04,1.061268,2017-05-04 00:00:00,603616.XSHG,27.80,27.80,27.80,24.41,25.37,34388364.0,0.0,...,81594848.0,3.0,1.0,32.20,0.0,09:30:00,False,1510.0,False,0.456331
002282.XSHE_2017-05-15,1.066886,2017-05-15 00:00:00,002282.XSHE,20.14,20.14,20.14,17.90,18.32,40442093.0,7.0,...,75888049.0,10.0,3.0,23.97,0.0,09:30:00,False,1526.5,False,0.461318
002868.XSHE_2017-05-12,1.077338,2017-05-12 00:00:00,002868.XSHE,35.26,35.26,35.26,35.26,35.26,40950.0,5.0,...,17519293.0,8.0,8.0,41.58,0.0,09:30:00,False,253.0,True,0.076458
000852.XSHE_2017-05-18,1.087119,2017-05-18 00:00:00,000852.XSHE,13.28,13.40,14.18,12.46,12.58,44472076.0,10.0,...,90122477.0,13.0,2.0,14.34,61709800.0,13:15:00,False,2460.5,False,0.743578
002282.XSHE_2017-05-12,1.088036,2017-05-12 00:00:00,002282.XSHE,18.31,18.72,20.81,17.10,18.49,35610590.0,6.0,...,22941481.0,9.0,2.0,21.52,5563451.0,09:31:00,False,1378.0,False,0.416440
603896.XSHG_2017-05-25,1.089972,2017-05-25 00:00:00,603896.XSHG,32.05,32.05,32.05,27.38,28.02,19029139.0,9.0,...,7382684.0,12.0,3.0,36.00,9798200.0,09:57:00,False,317.0,True,0.095799
002616.XSHE_2017-05-16,1.098684,2017-05-16 00:00:00,002616.XSHE,21.35,21.77,23.25,20.80,20.99,10766611.0,8.0,...,51116103.0,11.0,2.0,11.96,60167800.0,14:20:00,False,1872.0,False,0.565730
300140.XSHE_2017-05-19,1.099792,2017-05-19 00:00:00,300140.XSHE,15.90,16.13,16.13,15.02,15.20,13710457.0,11.0,...,57383803.0,14.0,2.0,18.35,4417800.0,09:32:00,False,1535.0,False,0.463886
603505.XSHG_2017-05-24,1.099867,2017-05-24 00:00:00,603505.XSHG,18.62,18.62,18.62,18.62,18.62,667938.0,13.0,...,45122233.0,16.0,16.0,20.25,11521900.0,09:37:00,False,318.0,True,0.096102
300374.XSHE_2017-05-16,1.099931,2017-05-16 00:00:00,300374.XSHE,23.82,24.68,25.29,22.69,22.85,13649181.0,8.0,...,30770863.0,11.0,2.0,28.40,0.0,09:30:00,False,1009.0,False,0.304926
300649.XSHE_2017-05-24,1.210140,2017-05-24 00:00:00,300649.XSHE,37.16,37.16,37.16,37.16,37.16,124500.0,11.0,...,3961100.0,14.0,14.0,42.88,0.0,09:30:00,False,46.0,True,0.013901
002350.XSHE_2017-05-09,1.210269,2017-05-09 00:00:00,002350.XSHE,16.90,17.25,18.71,16.76,16.80,1600783.0,3.0,...,895214.0,6.0,2.0,19.39,4559200.0,09:31:00,False,1425.0,False,0.430644
603896.XSHG_2017-05-26,NaN,2017-05-26 00:00:00,603896.XSHG,35.26,35.26,35.26,31.09,31.10,17344531.0,10.0,...,NaN,NaN,4.0,41.58,0.0,09:30:00,False,353.5,True,0.106830
300140.XSHE_2017-05-26,NaN,2017-05-26 00:00:00,300140.XSHE,21.57,22.28,22.44,18.36,18.97,59912983.0,16.0,...,NaN,NaN,2.0,24.11,31073800.0,10:18:00,False,1926.0,False,0.582049
002350.XSHE_2017-05-26,NaN,2017-05-26 00:00:00,002350.XSHE,27.30,27.45,30.35,24.83,24.83,44330778.0,11.0,...,NaN,NaN,2.0,32.50,0.0,09:30:00,False,2198.5,False,0.664400
603098.XSHG_2017-05-26,NaN,2017-05-26 00:00:00,603098.XSHG,23.99,23.99,23.99,21.61,22.05,7102471.0,16.0,...,NaN,NaN,3.0,28.08,4358700.0,09:33:00,False,463.0,False,0.139921
601101.XSHG_2017-05-26,NaN,2017-05-26 00:00:00,601101.XSHG,6.76,6.79,7.57,6.51,6.70,8407282.0,16.0,...,NaN,NaN,2.0,7.79,14602000.0,09:41:00,False,2515.0,False,0.760048
002011.XSHE_2017-05-26,NaN,2017-05-26 00:00:00,002011.XSHE,10.87,10.87,10.87,9.50,9.90,53096183.0,16.0,...,NaN,NaN,3.0,12.71,23075000.0,09:32:00,False,2622.0,False,0.792384

In [9]:
data_df["change"].mean()

1.0117910735214655

In [10]:
data_df = data_df[~data_df["minute_low"].isnull()]
data_df = data_df[data_df["st"] == False]

In [11]:
data_df["change"].mean()

0.9801450440017141